config/routes.rb
Rails.application.routes.draw do

  resources :keywords
  # ## #### ## ## ## ## ## ## ## ## ## ## ## 
  # Devise
  # 
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    registrations: 'users/registrations'
    #omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    match '/users/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session_path, via: [:get, :delete]
  end

  get 'sign_in', to: redirect('/users/sign_in')
  get 'sign_out', to: redirect('/users/sign_out')
  get 'sign_up', to: redirect('/users/sign_up')
  get 'edit_registration', to: redirect('/users/edit')

  get 'users', to: redirect("sign_up")

  # ## #### ## ## ## ## ## ## ## ## ## ## ## 
  # Loader.io add-on
  # 
  get ENV['LOADER_IO'], to: "home#loaderio"

  # ## #### ## ## ## ## ## ## ## ## ## ## ## 
  # Generic Routes
  # 
  get 'home/index'
  get 'about', to: 'high_voltage/pages#show', id: 'about'
  get 'ajax', to: 'high_voltage/pages#show', id: 'ajax'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/keyword.rb
class Keyword < ApplicationRecord  
  NUMBER_OF_TWEETS = 50

  has_many :tweets
  
  validates :word, presence: true

  # Carrier Wave
  mount_uploader :image, ImageUploader
  
  def collect_tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_CONSUMER_KEY']
      config.consumer_secret     = ENV['TWITTER_CONSUMER_SECRET']
      config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
      config.access_token_secret = ENV['TWITTER_ACCESS_SECRET']
    end  
    
    # Create a collection of Tweets that match the search keyword
    client.search(self.word, count: NUMBER_OF_TWEETS, result_type: "recent", lang: "en").take(NUMBER_OF_TWEETS).collect do |t|
      tweet = Tweet.new if t.is_a?(Twitter::Tweet)
      tweet.tweet_id         = t.id.to_s
      tweet.tweet_created_at = tweet.created_at
      tweet.text             = t.text
      tweet.user_uid         = t.user.id
      tweet.user_name        = t.user.name
      tweet.user_screen_name = t.user.screen_name
      tweet.user_image_url   = t.user.profile_image_url
      tweet.keyword          = self
      
      tweet.save
    end
  end
  
  # Grant a specific number of Tweets for each keyword
  def self.collect_all_tweets
    Keyword.all.each do |keyword|
      keyword.collect_tweets
    end
    # Memcachier that clears a fragment
    ActionController::Base.new.expire_fragment('keywords_index_table')
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  include ApplicationHelper
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    num_of_tweets = 100
    @tweets = @keyword.tweets.order("created_at DESC").page(params[:page]).per_page(num_of_tweets)
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    # CHANGED - If a user does not submit a word, do not continue forward.
    @keyword.collect_tweets unless @keyword.word.blank?

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      
      @keyword.collect_tweets unless @keyword.word.blank?      
      
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:word, :image)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.haml
= simple_form_for @keyword, html: {multipart: true} do |f|
  = f.error_notification

  .form-inputs
    = f.input :word

  .form-inputs
    = image_tag @keyword.image_url if @keyword.image?
    = f.file_field :image
    = f.hidden_field :image_cache

  .form-actions
    = f.button :submit

app/views/keywords/edit.html.haml
%h1 Editing keyword

= render 'form'

= link_to 'Show', @keyword
\|
= link_to 'Back', keywords_path

app/views/keywords/index.html.haml
%h1 Listing keywords

%span{style:"float:right;"}
  = link_to 'New Keyword', new_keyword_path, class: "btn btn-primary"

- cache "keywords_index_table", skip_digest: true do
  %table.table.table-striped
    %thead
      %tr
        %th Icon
        %th Keyword
        %th Count
        %th 
        %th
        %th
  
    %tbody
      - @keywords.each do |keyword|
        %tr
          %td= image_tag keyword.image.thumb.url unless keyword.image.thumb.url.blank?
          %td= keyword.word
          %td= keyword.tweets.count
          %td= link_to 'Show', keyword, class: "btn btn-default"
          %td= link_to 'Edit', edit_keyword_path(keyword), class: "btn btn-primary"
          %td= link_to 'Destroy', keyword, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"
  

app/views/keywords/new.html.haml
%h1 New keyword

= render 'form'

= link_to 'Back', keywords_path

app/views/keywords/show.html.haml
%p#notice= notice

%h1= @keyword.word
%div
  = image_tag @keyword.image.thumb.url if @keyword.image?

%hr

- cache "keywords_show_id_#{@keyword.id}_page_#{params[:page]}", skip_digest: true, expires_in: 5.minutes do

  %h3 Latest Tweets (#{@keyword.tweets.count})
  %ul
    - @tweets.each do |tweet|
      %li
        = image_tag tweet.user_image_url
        = tweet.text


  = will_paginate @tweets

%br

= link_to 'Edit', edit_keyword_path(@keyword)
\|
= link_to 'Back', keywords_path